apiVersion: v1
kind: ResourceQuota
metadata:
  name: microservices-quota
  namespace: {{ .Values.namespace }}
spec:
  hard:
    requests.cpu: "1.5"
    requests.memory: 3.0Gi
    limits.cpu: "5"
    limits.memory: 6.0Gi
