apiVersion: v1
kind: ResourceQuota
metadata:
  name: microservices-quota
  namespace: {{ .Values.namespace }}
spec:
  hard:
    requests.cpu: "4.0"
    requests.memory: 6.0Gi
    limits.cpu: "10"
    limits.memory: 12.0Gi
