{{- range $name, $svc := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    {{- include "microservices.labels" $ | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ $name }}
  ports:
    - name: http
      port: {{ $svc.port }}
      targetPort: http
{{- end }}
